
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A764B5F9DCEEE203180194F93875A827'
    
_lr_action_items = {'TIMEOUT':([6,16,],[7,7,]),'NUMBER':([13,15,],[17,18,]),'OPEN_CURLY_BRACKET':([5,],[6,]),'COLON':([7,9,],[13,15,]),'PRIORITY':([6,16,],[9,9,]),'QUERY':([0,],[2,]),'$end':([1,5,14,],[0,-38,-39,]),'CLOSE_CURLY_BRACKET':([8,10,11,12,17,18,19,],[14,-43,-42,-41,-44,-45,-40,]),'SLASH':([3,],[4,]),'COMMA':([10,11,12,17,18,],[-43,-42,16,-44,-45,]),'IDENTIFIER':([2,4,],[3,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query_option_list':([6,16,],[8,19,]),'query':([0,],[1,]),'priority':([6,16,],[10,10,]),'timeout':([6,16,],[11,11,]),'query_option':([6,16,],[12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('unit -> definition_list','unit',1,'p_unit','parsing.py',117),
  ('definition_list -> definition definition_list','definition_list',2,'p_definition_list','parsing.py',124),
  ('definition_list -> definition','definition_list',1,'p_definition_list','parsing.py',125),
  ('definition -> define_service','definition',1,'p_definition','parsing.py',137),
  ('definition -> define_client','definition',1,'p_definition','parsing.py',138),
  ('define_service -> SERVICE IDENTIFIER OPEN_CURLY_BRACKET settings operation_list CLOSE_CURLY_BRACKET','define_service',6,'p_define_service','parsing.py',145),
  ('define_service -> SERVICE IDENTIFIER OPEN_CURLY_BRACKET operation_list CLOSE_CURLY_BRACKET','define_service',5,'p_define_service','parsing.py',146),
  ('settings -> SETTINGS OPEN_CURLY_BRACKET setting_list CLOSE_CURLY_BRACKET','settings',4,'p_settings','parsing.py',157),
  ('setting_list -> setting setting_list','setting_list',2,'p_setting_list','parsing.py',164),
  ('setting_list -> setting','setting_list',1,'p_setting_list','parsing.py',165),
  ('setting -> queue','setting',1,'p_setting','parsing.py',177),
  ('setting -> autoscaling','setting',1,'p_setting','parsing.py',178),
  ('setting -> throttling','setting',1,'p_setting','parsing.py',179),
  ('queue -> QUEUE COLON LIFO','queue',3,'p_queue','parsing.py',186),
  ('queue -> QUEUE COLON FIFO','queue',3,'p_queue','parsing.py',187),
  ('throttling -> THROTTLING COLON NONE','throttling',3,'p_throttling','parsing.py',201),
  ('throttling -> THROTTLING COLON TAIL_DROP OPEN_BRACKET NUMBER CLOSE_BRACKET','throttling',6,'p_throttling','parsing.py',202),
  ('autoscaling -> AUTOSCALING OPEN_CURLY_BRACKET autoscaling_setting_list CLOSE_CURLY_BRACKET','autoscaling',4,'p_autoscaling','parsing.py',212),
  ('autoscaling_setting_list -> autoscaling_setting autoscaling_setting_list','autoscaling_setting_list',2,'p_autoscaling_setting_list','parsing.py',219),
  ('autoscaling_setting_list -> autoscaling_setting','autoscaling_setting_list',1,'p_autoscaling_setting_list','parsing.py',220),
  ('autoscaling_setting -> PERIOD COLON NUMBER','autoscaling_setting',3,'p_autoscaling_setting','parsing.py',232),
  ('autoscaling_setting -> LIMITS COLON OPEN_SQUARE_BRACKET NUMBER COMMA NUMBER CLOSE_SQUARE_BRACKET','autoscaling_setting',7,'p_autoscaling_setting','parsing.py',233),
  ('operation_list -> define_operation operation_list','operation_list',2,'p_operation_list','parsing.py',245),
  ('operation_list -> define_operation','operation_list',1,'p_operation_list','parsing.py',246),
  ('define_client -> CLIENT IDENTIFIER OPEN_CURLY_BRACKET EVERY NUMBER OPEN_CURLY_BRACKET action_list CLOSE_CURLY_BRACKET CLOSE_CURLY_BRACKET','define_client',9,'p_define_client','parsing.py',258),
  ('define_operation -> OPERATION IDENTIFIER OPEN_CURLY_BRACKET action_list CLOSE_CURLY_BRACKET','define_operation',5,'p_define_operation','parsing.py',265),
  ('action_list -> action action_list','action_list',2,'p_action_list','parsing.py',272),
  ('action_list -> action','action_list',1,'p_action_list','parsing.py',273),
  ('action -> invoke','action',1,'p_action','parsing.py',285),
  ('action -> query','action',1,'p_action','parsing.py',286),
  ('action -> think','action',1,'p_action','parsing.py',287),
  ('action -> fail','action',1,'p_action','parsing.py',288),
  ('action -> retry','action',1,'p_action','parsing.py',289),
  ('action -> ignore','action',1,'p_action','parsing.py',290),
  ('think -> THINK NUMBER','think',2,'p_think','parsing.py',297),
  ('fail -> FAIL NUMBER','fail',2,'p_fail','parsing.py',304),
  ('fail -> FAIL','fail',1,'p_fail','parsing.py',305),
  ('query -> QUERY IDENTIFIER SLASH IDENTIFIER','query',4,'p_query','parsing.py',314),
  ('query -> QUERY IDENTIFIER SLASH IDENTIFIER OPEN_CURLY_BRACKET query_option_list CLOSE_CURLY_BRACKET','query',7,'p_query','parsing.py',315),
  ('query_option_list -> query_option COMMA query_option_list','query_option_list',3,'p_query_option_list','parsing.py',325),
  ('query_option_list -> query_option','query_option_list',1,'p_query_option_list','parsing.py',326),
  ('query_option -> timeout','query_option',1,'p_query_option','parsing.py',338),
  ('query_option -> priority','query_option',1,'p_query_option','parsing.py',339),
  ('timeout -> TIMEOUT COLON NUMBER','timeout',3,'p_timeout','parsing.py',346),
  ('priority -> PRIORITY COLON NUMBER','priority',3,'p_priority','parsing.py',353),
  ('invoke -> INVOKE IDENTIFIER SLASH IDENTIFIER','invoke',4,'p_invoke','parsing.py',360),
  ('invoke -> INVOKE IDENTIFIER SLASH IDENTIFIER OPEN_CURLY_BRACKET PRIORITY COLON NUMBER CLOSE_CURLY_BRACKET','invoke',9,'p_invoke','parsing.py',361),
  ('retry -> RETRY OPEN_CURLY_BRACKET action_list CLOSE_CURLY_BRACKET','retry',4,'p_retry','parsing.py',371),
  ('retry -> RETRY OPEN_BRACKET retry_option_list CLOSE_BRACKET OPEN_CURLY_BRACKET action_list CLOSE_CURLY_BRACKET','retry',7,'p_retry','parsing.py',372),
  ('retry_option_list -> retry_option COMMA retry_option_list','retry_option_list',3,'p_retry_option_list','parsing.py',384),
  ('retry_option_list -> retry_option','retry_option_list',1,'p_retry_option_list','parsing.py',385),
  ('retry_option -> LIMIT COLON NUMBER','retry_option',3,'p_retry_option','parsing.py',397),
  ('retry_option -> DELAY COLON IDENTIFIER OPEN_BRACKET NUMBER CLOSE_BRACKET','retry_option',6,'p_retry_option','parsing.py',398),
  ('ignore -> IGNORE OPEN_CURLY_BRACKET action_list CLOSE_CURLY_BRACKET','ignore',4,'p_ignore','parsing.py',410),
]
